[package]
name = "b"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
clap = { version = "4.5.11", features = ["derive"] }
ctrlc = "3.4.4"
fern = "0.6.2"
log = "0.4.22"
serde = { version = "1.0.204", features = ["derive"] }
sha2 = "0.10.8"
